---
- name: Install EPEL repository
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - java-1.8.0-openjdk
      - perl
      - rsync
      - ruby
      - rubygem-io-console
      - rubygem-net-ssh
      - rubygem-net-scp
      - tar
      - zip
