---
- name: Install EPEL repository
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - java-1.8.0-openjdk
      - perl
      - rsync
      - ruby
      - rubygem-io-console
      - rubygem-net-ssh
      - rubygem-net-scp
      - tar
      - zip

- name: Install Percona XtraBackup
  yum:
    name: "https://www.percona.com/downloads/Percona-XtraBackup-2.4/Percona-XtraBackup-2.4.16/binary/redhat/7/x86_64/percona-xtrabackup-24-2.4.16-1.el7.x86_64.rpm"
    state: present
