---
- name: Update all packages
  shell: apt update
  become: yes

- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - build-essential
      - nfs-common
      - openjdk-8-jdk
      - perl
      - rsync
      - ruby
      - ruby-dev
      - rubygems
      - tar
      - zip

- name: Install Ruby gems
  shell: "gem install {{ item }}"
  become: yes
  with_items:
    - io-console
    - net-ssh
    - net-scp

- name: Install Percona XtraBackup
  apt:
    deb: "https://repo.percona.com/apt/percona-release_latest.bionic_all.deb"
