---
- name: Ensure root can login into MySQL localhost
  shell: "mysql -e \"CREATE USER 'root'@'{{ item }}' IDENTIFIED BY '{{ passwd_mysql_root }}';\" -uroot -p'{{ passwd_mysql_root }}'"
  with_items:
    - ::1
    - 127.0.0.1
    - localhost
  ignore_errors: yes

- name: Create the MySQL tungsten user
  shell: "mysql -e \"CREATE USER 'tungsten'@'{{ item }}' IDENTIFIED BY '{{ passwd_mysql_tungsten }}'; GRANT ALL PRIVILEGES ON *.* TO 'tungsten'@'{{ item }}' WITH GRANT OPTION;\" -uroot -p'{{ passwd_mysql_root }}'"
  with_items:
    - ::1
    - 127.0.0.1
    - localhost
    - "%"
    - "{{ ansible_facts['hostname'] }}"

- name: Create the MySQL app_user
  shell: "mysql -e \"CREATE USER 'app_user'@'{{ item }}' IDENTIFIED BY '{{ passwd_mysql_app_user }}'; GRANT ALL PRIVILEGES ON *.* TO 'app_user'@'{{ item }}';\" -uroot -p'{{ passwd_mysql_root }}'"
  with_items:
    - "%"
    - "{{ ansible_facts['hostname'] }}"

- name: Revoke the SUPER privileges from the MySQL app_user
  shell: "mysql -NBe \"REVOKE SUPER ON *.* FROM app_user@'{{ item }}'\" -uroot -p'{{ passwd_mysql_root }}'"
  with_items:
    - "%"
    - "{{ ansible_facts['hostname'] }}"

- name: Adding user mysql to group tungsten
  user:
    name: mysql
    groups: tungsten
    append: yes

- name: Copy root .my.cnf file
  template:
    src: ../../templates/root-my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Copy tungsten .my.cnf file
  template:
    src: ../../templates/tungsten-my.cnf.j2
    dest: /home/tungsten/.my.cnf
    owner: tungsten
    group: tungsten
    mode: 0600

- name: Restart the MySQL service
  shell: service mysql restart
  become: yes
