---
- name: Install MySQL packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mysql-common
      - mysql-server
      - mysql-client

- name: Enable the MySQL service
  service:
    name: mysql
    state: started
    enabled: true

- name: Generate MySQL server-id
  shell: hostname -I | sed -e 's/ \+\([a-z0-9]\+\:\)\+[a-z0-9]\+//' | sed -e 's/ /\n/' | grep -v '^$' | tail -1 | awk -F. '{print $3 * 256 + $4}'
  register: mysql_server_id

- name: Create /etc/my.cnf
  template:
    src: ../../templates/mysql_debian.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
    backup: true

- name: Create /etc/init.d/mysqld file
  copy:
    src: ../../files/mysqld
    dest: /etc/init.d/mysqld
    owner: root
    group: root
    mode: 0755
